version: '3'
services:
  octoprint-klipper:
    image: "chevellabv/octoprint-klipper:arm"
    container_name: "octoprint-klipper"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/video0:/dev/video0"
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/usbstick/octoprint-klipper-volume:/home/octoprint/.octoprint"
    environment:
      TZ: Europe/Amsterdam
    restart: unless-stopped
